version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # docs
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  # spry
  - package-ecosystem: pub
    directory: /packages/spry
    schedule:
      interval: daily
