name: spry_fsrouter
description: Define Spry router in the way of filesystem router layout, it builds on top of Spry router, supports group route mount, nested route, handler mount, middleware, etc.
version: 1.1.1
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_fsrouter

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  args: ^2.3.1
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  freezed_annotation: ^2.2.0
  http_methods: ^1.1.0
  json_annotation: ^4.7.0
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  spry: ^2.3.0
  test: ^1.16.0
