name: spry_router
description: A request router for the Spry web framework that supports matching handlers from path expressions.
version: 0.5.0
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_router

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  http_methods: ^1.1.0
  prexp: ^0.1.1
  spry: ">=0.4.0 <0.6.0"

dev_dependencies:
  lints: ^2.0.0
