name: spry_static
description: Static files handler support for Spry and ecosystem.
version: 0.0.1
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_static

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  mime: ^1.0.3
  path: ^1.8.3
  prexp: ^0.1.1
  spry: ^0.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
